services:
  db-pokemon:
    image: mysql:5.7
    container_name: db-pokemon
    restart: always
    env_file:
      - path: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./db-pokemon/data:/var/lib/mysql"