services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    image: app
    depends_on:
      - db
      - redis
    ports:
      - '8080:80'
    volumes:
      - .:/app
    networks:
      - src_default

  redis:
    container_name: redis
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - src_default

  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    expose:
      - "3306"
    networks:
      - src_default

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ".:/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
    networks:
      - src_default

networks:
  src_default:

volumes:
  mysql:
    driver: local
  redis:
    driver: local
