services:
  db:
    container_name: db
    image: mysql:8.0.34
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_USERNAME=${DB_ROOT_USERNAME}
    volumes:
      - "./application_data/db/data:/var/lib/mysql"
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - src_default


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    volumes:
      - "./application_data/redis/data:/root/redis"
    networks:
      - src_default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ".:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - src_default

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www"
    networks:
      - src_default

  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: horizon
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - nginx
    command: ["sh","/var/www/entrypoint.sh"]
    volumes:
      - ".:/var/www"
    networks:
      - src_default
networks:
  src_default:
    driver: bridge
