services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    ports:
      - "9000:9000"
    volumes:
      - ".:/app"
    networks:
      - src_default

  db:
    image: mysql:8.0.34
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./application_data/db/data:/var/lib/mysql"
    networks:
      - src_default
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    volumes:
      - "./application_data/redis/data:/root/redis"
    networks:
      - src_default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app"
    depends_on:
      - app
    networks:
      - src_default
networks:
  src_default:

volumes:
  db:
    driver: local
  redis:
    driver: local