services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    env_file:
      - path: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./application_data/db/data:/var/lib/mysql"
    networks:
      - laravel_app
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - path: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    volumes:
      - "./application_data/redis/data:/root/redis"
    networks:
      - laravel_app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    volumes:
      - ".:/var/www/html"
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge