services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    env_file:
      - path: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./application_data/db/data:/var/lib/mysql"
    networks:
      - src_default
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - path: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    volumes:
      - "./application_data/redis/data:/root/redis"
    networks:
      - src_default
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ".:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - src_default

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - nginx
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www"
    networks:
      - src_default
networks:
  src_default:
    driver: bridge