services:
  db-pokemon:
    image: mysql:5.7
    container_name: db-pokemon
    restart: always
    env_file:
      - path: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./db-pokemon/data:/var/lib/mysql"
  
  redis-server:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - path: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    volumes:
      - "./redis-server/data:/root/redis"