services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    ports:
      - "8080:80"
    volumes:
      - ".:/app"
    networks:
      - src_default

  db:
    image: mysql:8.0.34
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "./application_data/db/data:/var/lib/mysql"
    networks:
      - src_default
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=redis
    volumes:
      - "./application_data/redis/data:/root/redis"
    networks:
      - src_default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app"
    depends_on:
      - app
    networks:
      - src_default
networks:
  src_default:

volumes:
  db:
    driver: local
  redis:
    driver: local